name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  backend-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Backend workflow triggered successfully!"